spring:
  application:
    name: api-gateway

server:
  port: 5555

eureka:
  client:
    serviceUrl:
      defaultZone: http://syc:123456@localhost:8761/eureka/,http://syc:123456@localhost:8762/eureka/

# 面想服务的路由配置
# 更简介的配置方式： zuul.routes.<serviceId>=<path>
# example:        zuul.routes.hello-service-1=/api-a/**

# 最简单的方式是使用zuul 提供的默认路由方式,不需要任何配，zuul默认做了如下配置:
#      zuul.routes.<serviceId>.path=/<serviceId>/**
#      zuul.routes.<serviceId>.serviceId=<serviceId>
zuul:
  routes:
    api-a:
      path: /api-a/**
      serviceId: hello-service-1
    api-b:
      path: /api-b/**
      serviceId: feign-consumer
  filter:
    root: filter
    interval: 5
