spring:
  application:
    name: feign-consumer
  cloud:
    loadbalancer:
      retry:
        enabled: true

eureka:
  client:
    serviceUrl:
      defaultZone: http://syc:123456@localhost:8761/eureka/
    healthcheck:
      enabled: true

server:
  port: 9091

# 超时重试？？

HELLO-SERVICE-1:
  ribbon:
    ConnectTimeout: 500
    ReadTimeout: 1000
    OkToRetryOnAllOperations: true
    MaxAutoRetriesNextServer: 2
    MaxAutoRetries: 3
