spring:
  application:
    name: ribbon-consumer
  cloud:
    loadbalancer:
      retry:
        enabled: true

eureka:
  client:
    serviceUrl:
      defaultZone: http://syc:123456@localhost:8761/eureka/
    healthcheck:
      enabled: true

server:
  port: 9001

# 超时重试？？