server:
  port: 8762
eureka:
  instance:
    hostname: syc-tk
  client:
#    registerWithEureka: false
#    fetchRegistry: false
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
spring:
  application:
    name: eureka-server