server:
  port: 8761

eureka:
  instance:
    hostname: 172.17.0.3
    prefer-ip-address: true
  client:
#    registerWithEureka: false
#    fetchRegistry: false
    serviceUrl:
      defaultZone: http://172.17.0.4:8762/eureka/
  server:
    peer-node-read-timeout-ms: 2000
spring:
  application:
    name: eureka-server
