server:
  port: 8761

eureka:
  instance:
    hostname: localhsot
  client:
#    registerWithEureka: false
#    fetchRegistry: false
    serviceUrl:
      defaultZone: http://syc-tk:8762/eureka/
spring:
  application:
    name: eureka-server