server:
  port: 8761

eureka:
  instance:
    hostname: localhost
    prefer-ip-address: true
  client:
#    registerWithEureka: false
#    fetchRegistry: false
    serviceUrl:
      defaultZone: http://syc:123456@localhost:8762/eureka/
    healthcheck:
      enabled: true
  server:
    peer-node-read-timeout-ms: 2000
    # 分否进行自我保护
    enable-self-preservation: true
spring:
  application:
    name: eureka-server
