server:
  port: 8761

eureka:
  instance:
    hostname: localhost
    prefer-ip-address: true
  client:
#    registerWithEureka: false
#    fetchRegistry: false
    serviceUrl:
      defaultZone: http://localhost:8762/eureka/
  server:
    peer-node-read-timeout-ms: 2000
spring:
  application:
    name: eureka-server
