spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/erpang226/spring-config
          search-paths: spring-cloud-learning
          username: {username}
          password: {password}


server:
  port: 7001

