spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/erpang226/spring-config
          search-paths: spring-cloud-learning
          username: erpang226
          password: syc398399363


server:
  port: 7001

